import createClient from "openapi-fetch";
import { env } from "~/env";
import type { paths } from "./types.generated"; // generated by openapi-typescript

export const foApi = createClient<paths>({
	baseUrl: "https://fantasyonline2.com",
	headers: {
		"x-api-key": env.FO_API_KEY,
	},
	next: {
		revalidate: 300, // 5 mins
	},
});
